name: UniverseNextDoor
favicon: null
layout_spectrum: 0.76137
typography_spectrum: 0.1572
title: Universe Next Door
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dfdfdd'
    - '#acc7be'
    - '#72786e'
    - '#4a4a4a'
    - '#c48170'
  brandStrength: 0.5
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
