name: UniverseNextDoor
favicon: null
layout_spectrum: 0
typography_spectrum: 0.13636
title: Universe Next Door
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#010101'
    - '#999592'
    - '#3f3631'
    - '#ed6424'
  brandStrength: 0.5
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
