name: UniverseNextDoor
favicon: null
layout_spectrum: 0
typography_spectrum: 0.1572
title: Universe Next Door
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#4e335e'
    - '#c571af'
    - '#ba4673'
    - '#efaac1'
  brandStrength: 1
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
