name: UniverseNextDoor
favicon: null
layout_spectrum: 0.75568
typography_spectrum: 0.1572
title: Universe Next Door
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#211e1f'
    - '#56565f'
    - '#a6a5aa'
    - '#74747c'
  brandStrength: 0.6875
  lightness: 0.5625
  saturation: 0
  rhythmicContrast: 1
purpose: []
